version: "2.2"

services:
    autovoice:
        build:
            context: . 
            dockerfile: docker/dockerfile
        image: autovoicechannels:latest
        volumes:
            - type: volume
              source: guilds
              target: /Auto-voice-channels/guilds
        environment:
            - admin_id=764880242191892482
            - client_id=732585101400997909
            - log_timezone=Europe/London
            - token=NzMyNTg1MTAxNDAwOTk3OTA5.Xw2vCg.2t5AVYLa8SPhTKrU0LH7iXVmkpQ
volumes:
    guilds: