"""Generates bot/src/features/voice/unicodeFonts.generated.ts from Python's
unicodedata — the SAME source the legacy translate.py used — so the new bot's
font transforms are byte-for-byte identical to the legacy `mathematical_unicode`
and `small_caps`, including the legacy "holes" (names unicodedata can't resolve
fall back to the plain ASCII char, exactly as the legacy `except KeyError`).

Run: python scripts/gen-unicode-fonts.py
"""

import unicodedata
import os

DIGITS = {
    "0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
    "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine",
}

# legacy mode name -> "Mathematical <Mode>" string (from translate.py)
MATH_MODES = {
    "bold": "Bold",
    "italic": "Italic",
    "bolditalic": "Bold Italic",
    "script": "Script",
    "boldscript": "Bold Script",
    "fraktur": "Fraktur",
    "boldfraktur": "Bold Fraktur",
    "double": "Double-Struck",
    "sans": "Sans-Serif",
    "boldsans": "Sans-Serif Bold",
    "italicsans": "Sans-Serif Italic",
    "bolditalicsans": "Sans-Serif Bold Italic",
    "mono": "Monospace",
}

LETTERS = [chr(c) for c in range(ord("A"), ord("Z") + 1)] + [
    chr(c) for c in range(ord("a"), ord("z") + 1)
]
ALL = LETTERS + list("0123456789")


def math_char(mode_str, c):
    case = "Capital"
    nc = c
    if c.islower():
        case = "Small"
    if c.isdigit():
        case = "Digit"
        nc = DIGITS[c]
    try:
        return unicodedata.lookup("Mathematical {} {} {}".format(mode_str, case, nc))
    except KeyError:
        return c  # legacy hole -> plain char


def small_cap(c):
    if c.islower():
        try:
            return unicodedata.lookup("LATIN LETTER SMALL CAPITAL " + c)
        except KeyError:
            return c
    return c


def emit_map(name, mapping):
    # Only non-identity entries; everything else passes through at runtime.
    entries = [(k, v) for k, v in mapping.items() if v != k]
    body = ", ".join('"{}": "{}"'.format(k, v) for k, v in entries)
    return "  {}: {{ {} }},".format(name, body)


lines = [
    "// GENERATED by scripts/gen-unicode-fonts.py — do not edit by hand.",
    "// Static character maps ported from the legacy translate.py via Python",
    "// unicodedata (Unicode {}). Only non-identity chars are listed; anything".format(
        unicodedata.unidata_version
    ),
    "// absent (and the legacy KeyError 'holes') passes through unchanged.",
    "// prettier-ignore",
    "export const FONT_MAPS: Record<string, Record<string, string>> = {",
]
for mode, mode_str in MATH_MODES.items():
    lines.append(emit_map(mode, {c: math_char(mode_str, c) for c in ALL}))
lines.append("};")
lines.append("")
sc = {c: small_cap(c) for c in LETTERS}
sc_entries = ", ".join('"{}": "{}"'.format(k, v) for k, v in sc.items() if v != k)
lines.append(
    "export const SMALL_CAPS_MAP: Record<string, string> = { " + sc_entries + " };"
)
lines.append("")

out_path = os.path.join("bot", "src", "features", "voice", "unicodeFonts.generated.ts")
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("wrote", out_path, "with", len(MATH_MODES), "font maps + small caps")
